/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedActivateRouteImport } from './routes/_authenticated/activate'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as SSlugCheckoutRouteImport } from './routes/s.$slug.checkout'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as SSlugProductIdRouteImport } from './routes/s.$slug.product.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivateRoute = AuthenticatedActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/s/$slug/',
  path: '/s/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugCheckoutRoute = SSlugCheckoutRouteImport.update({
  id: '/s/$slug/checkout',
  path: '/s/$slug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const SSlugProductIdRoute = SSlugProductIdRouteImport.update({
  id: '/s/$slug/product/$id',
  path: '/s/$slug/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activate': typeof AuthenticatedActivateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/s/$slug/product/$id': typeof SSlugProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activate': typeof AuthenticatedActivateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/s/$slug/product/$id': typeof SSlugProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/activate': typeof AuthenticatedActivateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/s/$slug/product/$id': typeof SSlugProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/activate'
    | '/dashboard'
    | '/onboarding'
    | '/orders'
    | '/products'
    | '/settings'
    | '/api/public/paystack-webhook'
    | '/s/$slug/checkout'
    | '/s/$slug/'
    | '/s/$slug/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/activate'
    | '/dashboard'
    | '/onboarding'
    | '/orders'
    | '/products'
    | '/settings'
    | '/api/public/paystack-webhook'
    | '/s/$slug/checkout'
    | '/s/$slug'
    | '/s/$slug/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/activate'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/orders'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/api/public/paystack-webhook'
    | '/s/$slug/checkout'
    | '/s/$slug/'
    | '/s/$slug/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  SSlugCheckoutRoute: typeof SSlugCheckoutRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
  SSlugProductIdRoute: typeof SSlugProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activate': {
      id: '/_authenticated/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof AuthenticatedActivateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/s/$slug'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/checkout': {
      id: '/s/$slug/checkout'
      path: '/s/$slug/checkout'
      fullPath: '/s/$slug/checkout'
      preLoaderRoute: typeof SSlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/product/$id': {
      id: '/s/$slug/product/$id'
      path: '/s/$slug/product/$id'
      fullPath: '/s/$slug/product/$id'
      preLoaderRoute: typeof SSlugProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivateRoute: typeof AuthenticatedActivateRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivateRoute: AuthenticatedActivateRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  SSlugCheckoutRoute: SSlugCheckoutRoute,
  SSlugIndexRoute: SSlugIndexRoute,
  SSlugProductIdRoute: SSlugProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
